export { DetailPanel } from "./detail-panel"
export { DetailSection } from "./detail-section"
export { DetailHeader } from "./detail-header"
export { DetailKV } from "./detail-kv"
export { DetailStatGrid, DetailStatItem } from "./detail-stat-grid"
export { DetailChartBox } from "./detail-chart-box"
export { DetailKPIRow } from "./detail-kpi-row"

export type { DetailPanelProps } from "./detail-panel"
export type { DetailSectionProps } from "./detail-section"
export type { DetailHeaderProps } from "./detail-header"
export type { DetailKVProps } from "./detail-kv"
export type { DetailStatGridProps, DetailStatItemProps } from "./detail-stat-grid"
export type { DetailChartBoxProps } from "./detail-chart-box"
export type { DetailKPIRowProps } from "./detail-kpi-row"
