"""Integration test: verify Qlib can read data generated by QlibDumper.

Requires: pip install pyqlib
Skip if qlib not installed.
"""

import numpy as np
import pandas as pd
import pytest
from pathlib import Path

from src.services.qlib_dump import QlibDumper

qlib = pytest.importorskip("qlib", reason="qlib not installed")


@pytest.fixture
def populated_qlib_dir(tmp_path):
    """Create a Qlib data directory with realistic test data."""
    qlib_dir = str(tmp_path / "qlib_test")

    dates = pd.bdate_range("2026-01-05", periods=20).tolist()
    calendar = [d.strftime("%Y-%m-%d") for d in dates]

    symbols = ["sh600000", "sz000001", "sz300001"]
    rows = []
    rng = np.random.default_rng(42)

    for sym in symbols:
        base_price = rng.uniform(10, 50)
        for i, d in enumerate(dates):
            change = rng.normal(0, 0.02)
            price = base_price * (1 + change)
            rows.append({
                "date": d,
                "symbol": sym,
                "open": round(price * rng.uniform(0.99, 1.01), 2),
                "close": round(price, 2),
                "high": round(price * rng.uniform(1.0, 1.03), 2),
                "low": round(price * rng.uniform(0.97, 1.0), 2),
                "volume": float(rng.integers(500_000, 5_000_000)),
                "factor": 1.0,
            })
            base_price = price

    df = pd.DataFrame(rows)
    dumper = QlibDumper(qlib_dir)
    result = dumper.dump_dataframe(df, calendar, ["open", "close", "high", "low", "volume", "factor"])
    assert result.success is True
    return qlib_dir


@pytest.mark.integration
def test_qlib_init_and_read(populated_qlib_dir):
    """Verify Qlib can initialize with our generated data and read features."""
    import qlib
    from qlib.data import D

    qlib.init(provider_uri=populated_qlib_dir, region="cn")

    instruments = ["SH600000"]
    fields = ["$close", "$volume"]
    df = D.features(instruments, fields, start_time="2026-01-05", end_time="2026-01-30")

    assert not df.empty, "Qlib returned empty DataFrame"
    assert "$close" in df.columns
    assert "$volume" in df.columns
    assert len(df) > 0

    for col in df.columns:
        assert not df[col].isna().all(), f"Column {col} is all NaN"
