import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  Brain,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  Clock,
  Code2,
  Compass,
  Cpu,
  Database,
  Eye,
  Filter,
  FlaskConical,
  Gem,
  GitBranch,
  Grid3X3,
  HeartPulse,
  Info,
  Layers,
  LayoutDashboard,
  Library,
  LineChart,
  Lock,
  Monitor,
  MousePointerClick,
  Navigation,
  Newspaper,
  Pickaxe,
  Rocket,
  Rss,
  Search,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  Sparkles,
  Table2,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Wallet,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Maps icon name strings (from .md frontmatter) to Lucide icon components.
 *
 * When adding a new icon to a .md file, register it here.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  Brain,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  Clock,
  Code2,
  Compass,
  Cpu,
  Database,
  Eye,
  Filter,
  FlaskConical,
  Gem,
  GitBranch,
  Grid3X3,
  HeartPulse,
  Info,
  Layers,
  LayoutDashboard,
  Library,
  LineChart,
  Lock,
  Monitor,
  MousePointerClick,
  Navigation,
  Newspaper,
  Pickaxe,
  Rocket,
  Rss,
  Search,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  Sparkles,
  Table2,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Wallet,
  Zap,
};

/** Resolve an icon name string to a Lucide component. Returns Info as fallback. */
export function resolveIcon(name: string | undefined): LucideIcon {
  if (!name) return Info;
  return ICON_MAP[name] ?? Info;
}
